server:
  port: 7531
spring:
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, image
      routes:
        - id: api_route
          uri: http://localhost:7530
          predicates:
            - Path=/api/**

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

dubbo:
  application:
    name: dubbo-springboot-demo-provider
    qos-port: 22230
  protocol:
    name: dubbo
    port: 22224
  registry:
    id: nacos-registry
    address: nacos://localhost:8848